
name: Python Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run Flask app in the background
      if: ${{ github.event_name == 'push' }}
      run: |
        source venv/bin/activate
        export FLASK_APP=app.py
        export FLASK_ENV=development
        nohup flask run --port 3000 &
      env:
        CI: true
